### ISSUE TITLE
 code for performing model fine-tuning

### ISSUE THREAD

**Issue by Glisten-5481** [prachigarg23/MDIL-SS#5]
I'm sorry to disturb you, but if possible, could you provide the code for performing model fine-tuning? I'm sorry, but it seems I can't find the relevant code in the file list. Thank you very much for your help.

**Comment by prachigarg23** [comment]
Hi @Glisten-5481 , the fine-tuning files are `main_ftp1_enc_newbn.py` and `main_FT2_flexible_new.py` which seem to be already present in the repository. Can you please specify if you meant another missing file?
